// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FooService.proto

package org.example.grpc;

public interface FooRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.grpc.FooRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
