// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FooService.proto

package org.example.grpc;

public final class FooServiceProto {
  private FooServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_grpc_FooRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_grpc_FooRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_grpc_FooResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_grpc_FooResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FooService.proto\022\020org.example.grpc\"\035\n\n" +
      "FooRequest\022\017\n\007content\030\001 \001(\t\"\036\n\013FooRespon" +
      "se\022\017\n\007content\030\001 \001(\t2W\n\nFooService\022I\n\010Say" +
      "Hello\022\034.org.example.grpc.FooRequest\032\035.or" +
      "g.example.grpc.FooResponse\"\000B%\n\020org.exam" +
      "ple.grpcB\017FooServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_example_grpc_FooRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_grpc_FooRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_grpc_FooRequest_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_org_example_grpc_FooResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_grpc_FooResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_grpc_FooResponse_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
